version: '3.8'
services:
  db:
    container_name: MySql_Cliente
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: cliente
      MYSQL_USER: cliente
      MYSQL_PASSWORD: cliente
    volumes:
     - ./api/db/data:/var/lib/mysql
    restart: always 
    ports:
     - 3306:3306